[project]
name = "mcp-runtime-server"
version = "0.1.0"
description = "MCP Runtime Server for executing code in isolated environments"
requires-python = ">=3.8"
dependencies = [
    "git+https://github.com/modelcontextprotocol/python-sdk.git@main#egg=mcp",
    "uv==0.5.13",
    "pytest==8.0.0rc1",
    "pytest-cov==6.0.0",
    "pytest-asyncio==0.23.8", 
    "appdirs==1.4.4",
    "requests==2.31.0",
    "aiohttp==3.9.1",
    "colorlog==6.8.0",
    "typing_extensions==4.9.0",
    "colorama==0.4.6",
    "rich==13.7.0"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"

[project.scripts]
mcp-runtime-server = "mcp_runtime_server.server:main"

[tool.coverage.run]
source = ["mcp_runtime_server"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
