[project]
name = "mcp-runtime-server"
version = "0.1.0"
description = "MCP Runtime Server for executing code in isolated environments"
requires-python = ">=3.8"
dependencies = [
    "mcp",
    "appdirs"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
