[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mcp-runtime-server"
version = "0.1.0"
description = "Model Context Protocol Runtime Server - A secure sandbox for managing runtime environments"
requires-python = ">=3.9"
dependencies = [
    "mcp>=0.7.0",
    "aiohttp>=3.9.0",
    "psutil>=5.9.0",
    "appdirs>=1.4.4",
    "structlog>=23.0.0"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio",
    "pytest-cov",
    "black",
    "mypy",
    "ruff"
]

# Extra security features for Linux
linux = [
    "python-seccomp",  # For syscall filtering
    "python-unshare",  # For namespace isolation
]

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.mypy]
strict = true

[tool.ruff]
select = ["E", "F", "B"]
ignore = []