[project]
name = "mcp-runtime-server"
version = "0.1.0"
description = "MCP Runtime Server for executing code in isolated environments"
requires-python = ">=3.8"
dependencies = [
    "mcp>=0.1.0",
    "uv>=0.1.0",
    "pytest>=7.0.0",
    "pytest-cov>=4.1.0",
    "pytest-asyncio>=0.21.1",
    "appdirs>=1.4.4",
    "requests>=2.31.0",
    "aiohttp>=3.8.6",
    "colorlog>=6.7.0",
    "typing_extensions>=4.8.0",
    "colorama>=0.4.6",
    "rich>=13.0.0"
]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = "test_*.py"

[project.scripts]
mcp-runtime-server = "mcp_runtime_server.server:main"

[tool.coverage.run]
source = ["mcp_runtime_server"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
