[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "example"
version = "0.1.0"
description = "Example project for testing"
requires-python = ">=3.12"
dependencies = []
